language: bash
sudo: false
cache:
  - apt
os:
  - linux
addons:
  apt:
    packages:
    - build-essential
    - texlive-base
    - texlive-binaries
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-bibtex-extra
    - lmodern
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - texlive-science
    - latex-beamer
    - pgf
    - pandoc
    - unzip
    - git-core
  hosts:
    - travis.dev
env:
  global:
    - TEXMFLOCAL=/tmp/texmf/
# installing a couple of LaTeX packages from CTAN manually as the
# tlmgr command is mising on ubuntu/precise
before_script:
  - source ./tests/setup_bats.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi
  - mkdir -p $TEXMFLOCAL/tex/latex/
  - wget -q http://mirrors.ctan.org/install/macros/latex/contrib/tcolorbox.tds.zip
  - wget -q http://mirrors.ctan.org/macros/latex/contrib/floatflt.zip
  - unzip -qq tcolorbox.tds.zip -d $TEXMFLOCAL
  - unzip -qq floatflt.zip
  - cd ./floatflt/ && latex floatflt.ins && cd -
  - cp ./floatflt/floatflt.sty $TEXMFLOCAL/tex/latex/
  - texhash
script:
  - bats tests
notifications:
  email:
    on_success: never
  slack:
    secure: NBN4QhHuaXpwZIxUOzZi29Z4iW0EK/d2ID7zZqz+1RDO/9BD7QqX5unM/SFP46oTbhEqNH/vMLLMFQ9i9l7Z1i6Z6nCNRiLRIjgPSL+3GMamPQm1Pj4JaLkwLHogxHdRvozfU3tdSG9uGmK++Aak/NLC/i5TASGrBMgKrmXLXEk=
