language: bash
sudo: false
cache:
- apt
os:
- linux
addons:
  apt:
    packages:
    - build-essential
    - texlive-base
    - texlive-binaries
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-bibtex-extra
    - lmodern
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - texlive-science
    - latex-beamer
    - pgf
    - pandoc
    - unzip
    - git-core
  hosts:
  - travis.dev
env:
  global:
  - TEXMFLOCAL=/tmp/texmf/
before_script:
- source ./tests/setup_bats.sh
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi
- mkdir -p $TEXMFLOCAL/tex/latex/
- wget -q http://mirrors.ctan.org/install/macros/latex/contrib/tcolorbox.tds.zip
- wget -q http://mirrors.ctan.org/macros/latex/contrib/floatflt.zip
- unzip -qq tcolorbox.tds.zip -d $TEXMFLOCAL
- unzip -qq floatflt.zip
- cd ./floatflt/ && latex floatflt.ins && cd -
- cp ./floatflt/floatflt.sty $TEXMFLOCAL/tex/latex/
- texhash
script:
- bats tests
notifications:
  email:
    on_success: never
  slack:
    rooms:
    - secure: JEi0rqcU1DsXPvO1AKPxtSQqG51u55SbDxzLajjL97MdZAobghD1j933gqpAxrKRKXoaxRAHERV6ryMecnTY8TSz+EVgnYjfPvCINH6a5EnSQsVb3QcxCHHTXD+h8nRcdDnAO+xt2dQDGuSwHyEfPSYkzyK7EaZSIsUyBGhNUe8=
    - secure: OZvUL1TBdcab6at0ZPiKkD2SkeOXJ1FJBad2fPeBNZe8OGgLru+aXeNRXvfVNJBi3qOTjg9KWqrzs2BfNjA1u8jlXmyFxdC81keNkAE32h14smeKa80wZ51yeNmC9sTmO9glBG156C1oTte6wkf1KZjdSov9EpP26iRJ5XqilKI=
