language: bash
sudo: false
cache:
  - apt
os:
  - linux
#  - osx
# before_install:
#   - tlmgr install tcolorbox
addons:
  apt:
    packages:
    - build-essential
    - texlive-base
    - texlive-binaries
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-bibtex-extra
    - lmodern
    - texlive-fonts-recommended
    - texlive-latex-recommended
    - latex-beamer
    - pgf
    - pandoc
    - unzip
  hosts:
    - travis.dev
env:
  global:
    - TEXMFLOCAL=/tmp/texmf/
before_script:
  - source ./tests/setup_bats.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bats; fi
  - mkdir -p $TEXMFLOCAL/tex/latex/
  - curl http://mirrors.ctan.org/install/macros/latex/contrib/tcolorbox.tds.zip -o "$TEXMFLOCAL/tcolorbox.tds.zip"
  - unzip $TEXMFLOCAL/tcolorbox.tds.zip -d $TEXMFLOCAL
  - texhash
script:
  - bats tests
notifications:
  email:
    on_success: never
